# Generated by Django 2.1.7 on 2020-12-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='home1',
            name='text',
            field=models.TextField(null=True, verbose_name='Uzun İçerik'),
        ),
        migrations.AddField(
            model_name='home2',
            name='text',
            field=models.TextField(null=True, verbose_name='Uzun İçerik'),
        ),
        migrations.AddField(
            model_name='home3',
            name='text',
            field=models.TextField(null=True, verbose_name='Uzun İçerik'),
        ),
        migrations.AddField(
            model_name='home4',
            name='text',
            field=models.TextField(null=True, verbose_name='Uzun İçerik'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='content',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
    ]
