# Generated by Django 2.1.7 on 2020-12-13 19:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201213_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='FotoBaşlık')),
                ('image', models.ImageField(upload_to='fotolar/')),
            ],
        ),
        migrations.AlterField(
            model_name='home1',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Uzun İçerik'),
        ),
        migrations.AlterField(
            model_name='home2',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Uzun İçerik'),
        ),
        migrations.AlterField(
            model_name='home3',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Uzun İçerik'),
        ),
        migrations.AlterField(
            model_name='home4',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Uzun İçerik'),
        ),
    ]
