# Generated by Django 2.1.7 on 2020-12-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201213_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(null=True, upload_to='fotolar/'),
        ),
    ]
