# Generated by Django 2.1.7 on 2020-12-14 15:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201214_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='FotoBaşlık')),
                ('text', ckeditor.fields.RichTextField(null=True, verbose_name='Uzun İçerik')),
            ],
        ),
    ]
