# Generated by Django 2.1.7 on 2020-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_iletisim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Solüstbüyükbaşlık')),
                ('title2', models.CharField(max_length=100, verbose_name='Solüstküçükbaşlık')),
                ('title3', models.CharField(max_length=100, verbose_name='Anasayfabaşlık')),
            ],
        ),
        migrations.AlterField(
            model_name='iletisim',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
    ]
