# Generated by Django 2.1.7 on 2020-12-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bülten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bülten',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotolar/'),
        ),
    ]
