# Generated by Django 2.1.7 on 2020-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201214_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bülten',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='bülten',
            name='üstimage',
            field=models.ImageField(blank=True, null=True, upload_to='fotolar/'),
        ),
    ]
