# Generated by Django 2.1.7 on 2020-12-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201214_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='İsim ve Soyisim')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('text', models.TextField(verbose_name='mesaj')),
            ],
        ),
    ]
